INSERT INTO file_question (question_id, question_desc) VALUES ('1','1. You are almost never late for your appointments');
INSERT INTO file_question (question_id, question_desc) VALUES ('2','2. You like to be engaged in an active and fast-paced job');
INSERT INTO file_question (question_id, question_desc) VALUES ('3','3. You enjoy having a wide circle of acquaintances');
INSERT INTO file_question (question_id, question_desc) VALUES ('4','4. You feel involved when watching TV soaps');
INSERT INTO file_question (question_id, question_desc) VALUES ('5','5. You are usually the first to react to a sudden event: the telephone ringing or unexpected question');
INSERT INTO file_question (question_id, question_desc) VALUES ('6','6. You feel that the world is founded on compassion');
INSERT INTO file_question (question_id, question_desc) VALUES ('7','7. You think that everything in the world is relative');
INSERT INTO file_question (question_id, question_desc) VALUES ('8','8. Strict observance of the established rules is likely to prevent attaining a good outcome');
INSERT INTO file_question (question_id, question_desc) VALUES ('9','9. It is difficult to get you excited');
INSERT INTO file_question (question_id, question_desc) VALUES ('10','10. When making a decision, you rely more on your feelings than on analysis of the situation');
INSERT INTO file_question (question_id, question_desc) VALUES ('11','11. You often think about humankind and its destiny');
INSERT INTO file_question (question_id, question_desc) VALUES ('12','12. You believe the best decision is one which can be easily changed');
INSERT INTO file_question (question_id, question_desc) VALUES ('13','13. You often ponder the root cause of phenomena and things');
INSERT INTO file_question (question_id, question_desc) VALUES ('14','14. You prefer to act immediately rather than speculate about various options');
INSERT INTO file_question (question_id, question_desc) VALUES ('15','15. You trust reason rather than feelings');
INSERT INTO file_question (question_id, question_desc) VALUES ('16','16. You are inclined to rely more on improvisation than on prior planning');
INSERT INTO file_question (question_id, question_desc) VALUES ('17','17. You spend your leisure time actively socializing with a group of people, attending parties, shopping, etc.');
INSERT INTO file_question (question_id, question_desc) VALUES ('18','18. You usually plan your actions in advance');
INSERT INTO file_question (question_id, question_desc) VALUES ('19','19. Your actions are frequently influenced by your emotions');
INSERT INTO file_question (question_id, question_desc) VALUES ('20','20. You are a person somewhat reserved and distant in communication');
INSERT INTO file_question (question_id, question_desc) VALUES ('21','21. You know how to put every minute of your time to good purpose');
INSERT INTO file_question (question_id, question_desc) VALUES ('22','22. You often contemplate the complexity of life');
INSERT INTO file_question (question_id, question_desc) VALUES ('23','23. After prolonged socializing you feel you need to get away and be alone');
INSERT INTO file_question (question_id, question_desc) VALUES ('24','24. You often do jobs in a hurry');
INSERT INTO file_question (question_id, question_desc) VALUES ('25','25. You easily see the general principle behind specific occurrences');
INSERT INTO file_question (question_id, question_desc) VALUES ('26','26. You frequently and easily express your feelings and emotions');
INSERT INTO file_question (question_id, question_desc) VALUES ('27','27. You find it difficult to speak loudly');
INSERT INTO file_question (question_id, question_desc) VALUES ('28','28. You get bored if you have to read theoretical books');
INSERT INTO file_question (question_id, question_desc) VALUES ('29','29. You tend to sympathize with other people');
INSERT INTO file_question (question_id, question_desc) VALUES ('30','30. You value justice higher than mercy');
INSERT INTO file_question (question_id, question_desc) VALUES ('31','31. You rapidly get involved in the social life of a new workplace');
INSERT INTO file_question (question_id, question_desc) VALUES ('32','32. The more people you speak to, the better you feel');
INSERT INTO file_question (question_id, question_desc) VALUES ('33','33. You tend to rely on your experience rather than on theoretical alternatives');
INSERT INTO file_question (question_id, question_desc) VALUES ('34','34. As a rule, you proceed only when you have a clear and detailed plan');
INSERT INTO file_question (question_id, question_desc) VALUES ('35','35. You easily empathize with the concerns of other people');
INSERT INTO file_question (question_id, question_desc) VALUES ('36','36. Often you prefer to read a book than go to a party');
INSERT INTO file_question (question_id, question_desc) VALUES ('37','37. When with a group of people, you enjoy being directly involved and being at the centre of attention');
INSERT INTO file_question (question_id, question_desc) VALUES ('38','38. You are more inclined to experiment than to follow familiar approaches');
INSERT INTO file_question (question_id, question_desc) VALUES ('39','39. You are strongly touched by the stories about people`s troubles');
INSERT INTO file_question (question_id, question_desc) VALUES ('40','40. Deadlines seem to you to be of relative rather than absolute importance');
INSERT INTO file_question (question_id, question_desc) VALUES ('41','41. You prefer to isolate yourself from outside noises');
INSERT INTO file_question (question_id, question_desc) VALUES ('42','42. For you, it is easier to gain knowledge through hands-on experience than from books or manuals');
INSERT INTO file_question (question_id, question_desc) VALUES ('43','43. You think that almost everything can be analyzed');
INSERT INTO file_question (question_id, question_desc) VALUES ('44','44. For you, no surprises is better than surprises - bad or good ones');
INSERT INTO file_question (question_id, question_desc) VALUES ('45','45. You take pleasure in putting things in order');
INSERT INTO file_question (question_id, question_desc) VALUES ('46','46. You feel at ease in a crowd');
INSERT INTO file_question (question_id, question_desc) VALUES ('47','47. You have good control over your desires and temptations');
INSERT INTO file_question (question_id, question_desc) VALUES ('48','48. You easily understand new theoretical principles');
INSERT INTO file_question (question_id, question_desc) VALUES ('49','49. You usually place yourself nearer to the side than in the center of the room');
INSERT INTO file_question (question_id, question_desc) VALUES ('50','50. When solving a problem you would rather follow a familiar approach than seek a new one');
INSERT INTO file_question (question_id, question_desc) VALUES ('51','51. A thirst for adventure is something close to your heart');
INSERT INTO file_question (question_id, question_desc) VALUES ('52','52. When considering a situation you pay more attention to the current situation and less to a possible sequence of events');
INSERT INTO file_question (question_id, question_desc) VALUES ('53','53. When solving a problem you consider the rational approach to be the best');
INSERT INTO file_question (question_id, question_desc) VALUES ('54','54. You find it difficult to talk about your feelings');
INSERT INTO file_question (question_id, question_desc) VALUES ('55','55. Your decisions are based more on the feeling of a moment than on the thorough planning');
INSERT INTO file_question (question_id, question_desc) VALUES ('56','56. You prefer to spend your leisure time alone or relaxing in a tranquil atmosphere');
INSERT INTO file_question (question_id, question_desc) VALUES ('57','57. You feel more comfortable sticking to conventional ways');
INSERT INTO file_question (question_id, question_desc) VALUES ('58','58. You are easily affected by strong emotions');
INSERT INTO file_question (question_id, question_desc) VALUES ('59','59. You are always looking for opportunities');
INSERT INTO file_question (question_id, question_desc) VALUES ('60','60. As a rule, current preoccupations worry you more than your future plans');
INSERT INTO file_question (question_id, question_desc) VALUES ('61','61. It is easy for you to communicate in social situations');
INSERT INTO file_question (question_id, question_desc) VALUES ('62','62. You rarely deviate from your habits');
INSERT INTO file_question (question_id, question_desc) VALUES ('63','63. You willingly involve yourself in matters which engage your sympathies');
INSERT INTO file_question (question_id, question_desc) VALUES ('64','64. You easily perceive various ways in which events could develop');
